version: '3'

services:
  database:
    container_name: garner_db
    image: postgres
    environment:
      - POSTGRES_DB=garner_db
      - POSTGRES_USER=web
      - POSTGRES_PASSWORD=root
    ports:
      - "127.0.0.1:3333:3306"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - garner_network

volumes:
  postgres-data:

networks:
  garner_network:
    driver: bridge